[global]
file perms = 644
[formats]
simple = "%d %ms %V %m%n"
[rules]
#my_cat.INFO    >stdout; simple
#my_cat.INFO    "./demo.log",1MB*1 "demo-%d(%Y%m%d).#2s.log";simple
my_cat.INFO    "/data/log/run.log",2MB*2; simple
